### ISSUE TITLE
If: Expression syntax error

### ISSUE THREAD

**Issue by astrogeek03** [iraf-community/iraf#101]
Hi,
 I have IRAF installed  on my machine (version 2.16) and I am at the moment trying to set up my IRAF environment (with mkiraf, xgterm..the usual) but I am getting a "if: Expression syntax" error as I type cl into the xgterm window. Anyone encountered this error before?
Thanks,
Rach

**Comment by olebole** [comment]
Do you use the IRAF version that is [provided here](https://github.com/iraf-community/iraf/releases)?

**Comment by astrogeek03** [comment]
I am not sure from where the system admin installed IRAF on my machine but the login. cl files says ,"    logver = "IRAF V2.16 March 2012".

**Comment by olebole** [comment]
That is way too old (and unsupported), and I think that this is the problem.  You should upgrade to the version provided here (or install it from the distribution, supposed that you use Ubuntu/Debian/Mint Linux), or ask your sysadmins to fix this.

**Comment by astrogeek03** [comment]
Many thanks for the suggestion! I will try installing the current version.

**Comment by olebole** [comment]
This problem should be solved there, since cl is [completely rewritten](https://github.com/iraf-community/iraf/commits/master/unix/hlib/cl.sh) now as a posix shell script, [`cl.sh`](https://github.com/iraf-community/iraf/blob/master/unix/hlib/cl.sh), that was tested to work properly. Therefore I am closing this. Please re-open if the problem persists with the current version.
