### ISSUE TITLE
Transfering PyRAF repository to iraf-community

### ISSUE THREAD

**Issue by perrygreenfield** [iraf-community/iraf#120]
We have gotten approval to do this (finally). So we need to work out the logistics of this. On our end I think Joe Hunkeler can handle it on our side, but I believe he would also need access to make changes in this repository. Let me know what needs to be done.

**Comment by olebole** [comment]
Probably there are two ways: 
  * I could add you (and/or @jhunkeler) to the iraf-community organization and give you the access to create/migrate a repository, then you migrate yourself (and are still the only owner), and/or
  * add me as an admin to the pyraf repository so that I could transfer it (and you then could keep or remove your own rights as you wish)

**Comment by perrygreenfield** [comment]
Adding @junkeler is probably easiest. I think you can remove his privileges after it is done, right? The other may require going through the STScI bureaucracy to grant a privilege.

**Comment by pllim** [comment]
@rendinam might be able to help too.

**Comment by olebole** [comment]
I just invited @jhunkeler into iraf-community. After it is transferred, it may be useful to ad me to the admins of pyraf so that it is not left orphaned once you leave (or find someone else to take over :smiley:  ).

**Comment by perrygreenfield** [comment]
Absolutely!

**Comment by jhunkeler** [comment]
Transferred. All done. :rocket:

**Comment by olebole** [comment]
Thank you!
