### ISSUE TITLE
IRAF package for macOS

### ISSUE THREAD

**Issue by wuting2022** [iraf-community/iraf#219]
I'm sorry I may not have been clear about my purpose, I was actually trying to install IRAf for my Mac, but I couldn't find the package

**Comment by olebole** [comment]
What exactly do you want to do? It would be great if someone would create an IRAF installation package for macOS. However, I don't have much experience with macOS, so I can't help with the specifics (like the required tools, or best practises) there. 

What would be good in any case would be not to have a final package, but a script that does the actual packaging. This way, the packaging could be repeated when a new release of IRAF appears.

It would also probably be good to handle dependencies: usually, one would install PyRAF and/or x11iraf in parallel. PyRAF then would require a Python setup, while x11iraf needs an X11 server. Also, many people use it in conjunction with SAOImageDS9.

----
*I moved the issue to the IRAF repository, since it mainly affects IRAF itself.*

**Comment by olebole** [comment]
For a discussion, it would be useful not to just edit your initial statement, but to add a new comment. Also, I do not get an notification if just the statement was edited.

To install IRAF on a Mac, please follow the [installation instructions](https://iraf-community.github.io/install.html). You will need to compile it from sources, as described there.
