### ISSUE TITLE
Installing on ARMv7 Raspberry Pi

### ISSUE THREAD

**Issue by jrothenbro** [iraf-community/iraf#52]
I am attempting to install IRAF on an RPi running Ubuntu Mate 16.04.3 with an ARMv7 processor. I guess the first question is will this build of IRAF run on an ARM architecture?

I have attempted to install following the README.install build from source directions: 

  1) Download and unpack the source distribution file:

	% tar zxf /<path>/iraf-src.tar.gz	# unpack tar file
	% cd iraf.v2161				# go to the IRAF directory

  2) Execute the install script to create needed links:

	% ./install 		# execute the install script

  3) Configure the system for the proper architecture and build

	% make <arch>		# where <arch> is 'linux', 'macintel', etc
	% make sysgen

./install initially completes with errors

```
                             Editing Paths
                             -------------
[  OK  ]
Editing iraf/imdir/cache paths into system files ...           [ FAIL ]
   ***  File setup.csh not found.

                       Checking File Permissions
                       -------------------------
Checking iraf file permissions ...                             [ FAIL ]
   ***  File generic.e not found.
   ***  File mkpkg.e not found.
   ***  File rmbin.e not found.
   ***  File rmfiles.e not found.
   ***  File rpp.e not found.
   ***  File rtar.e not found.
   ***  File wtar.e not found.
   ***  File xc.e not found.
   ***  File xpp.e not found.
   ***  File xyacc.e not found.
   ***  File sgidispatch.e not found.
   ***  File /home/fhire/Downloads/iraf-master/unix/bin.linux/sgi2*.e not found.
Checking imdir permissions ...                                 [  OK  ]
Checking cache permissions ...                                 [  OK  ]

```
But the .e files are created after building in step 3. Trying ./install again only returns one error

```
                             Editing Paths
                             -------------
[  OK  ]
Editing iraf/imdir/cache paths into system files ...           [ FAIL ]
   ***  File setup.csh not found.

```
To see what would happen I still tried making an IRAF directory and running mkiraf. After creating the LOGIN.CL file cl returns

```
ERROR:  No /iraf/iraf.v2161/iraf-master//bin.linux/vocl.e binary found.
```

Please advise on any steps I may be missing. Thank you!

**Comment by olebole** [comment]
You should source the `unix/hlib/setup.sh` file before:
```
% source unix/hlib/setup.sh
% ecl
```
The `cl` script here still has the bug (fixed in #50) that it tries to run `vocl.e`, which is not there. You can try either `ecl`, or `cl -e`, or replace `vocl.e` in the `cl.sh` script with `ecl.e`.

Also note that Ubuntu 18.04 already ships with a precompiled version of IRAF; you also may want to try out that.

**Comment by steelewool** [comment]
I was able to clone and get things working when I used the version of the software in the iraf-community/iraf repository. But, I was never able to get the version from IRAF working on the Raspberry Pi. I'll follow your progress to see if I was doing something wrong when I made this attempt.

**Comment by olebole** [comment]
Closing since I guess this is fixed with #50 (and #53). The `File setup.csh not found.` error message is fixed with #51.
Please re-open if the problem persists after patching `cl.sh` or using `ecl.sh`.

**Comment by olebole** [comment]
@steelewool could you (in a new issue) describe the specific problems you have?

**Comment by jrothenbro** [comment]
Thanks Ole, sourcing setup.sh and modifying cl.sh worked perfectly. IRAF is now up and running.

**Comment by steelewool** [comment]
@olebole When I was having trouble getting the IRAF version I could not get anything to even compile. I did not do a very good job of tracking what the issues were. Since the version here is working on my Ubuntu and Raspberry Pi machines I'm not feeling super motivated to try again - unless I get caught up on my other tasks. I wasn't aware that IRAF was part of Ubuntu 18.04 that is something else I can consider putting on my todo list. I will have to look back at what issues I tried to make Fritz aware of when I tried to install/compile the version he put on github.
