### ISSUE TITLE
Problem with installation on Mac 10.14.4

### ISSUE THREAD

**Issue by pmassey** [iraf-community/iraf#82]
When I go to do the make on my Macbook Air (running Mojave and Xcode 10.2.1 with the command tools installed) I have the following issue:

bash-3.2$ make sysgen 2>&1 | tee build.log
Building the IRAF v2.16 software tree

Wed Apr 24 16:31:08 MST 2019

(util/mksysgen)
Clean 'macintel' host directories ....
Clean src directories ....
Clean 'macintel' bin directories ....
Cleaning spool files ....
+ set -e
+ sh -x setarch.sh
++ ls -d as
+ '[' as = as ']'
+ rm -rf as
+ ln -s as.macintel as
++ ls -d bin
+ '[' bin = bin ']'
+ rm -rf bin
+ ln -s bin.macintel bin
+ echo '----------------------- OS -----------------------------'
----------------------- OS -----------------------------
+ echo +
+
+ echo +
+
+ cd os
+ sh -x mkpkg.sh
+ set -e
+ echo '--------------------- OS ----------------------'
--------------------- OS ----------------------
+ zsvjmp='../as/zsvjmp.[sS]'
+ gcc -c -g -Wall -O2 -I/iraf/iraf/include -DNOVOS -Wall ../as/zsvjmp.s gmttolst.c irafpath.c prwait.c zalloc.c zawset.c zcall.c zdojmp.c zfacss.c zfaloc.c zfchdr.c zfdele.c zfgcwd.c zfinfo.c zfiobf.c zfioks.c zfiolp.c zfiomt.c zfiond.c zfiopl.c zfiopr.c zfiosf.c zfiotx.c zfioty.c zflink.c zfmkcp.c zfmkdr.c zfnbrk.c zfpath.c zfpoll.c zfprot.c zfrmdr.c zfrnam.c zfsubd.c zfunc.c zfutim.c zfxdir.c zgcmdl.c zghost.c zglobl.c zgmtco.c zgtenv.c zgtime.c zgtpid.c zintpr.c zlocpr.c zlocva.c zmain.c zmaloc.c zmfree.c zopdir.c zopdpr.c zoscmd.c zpanic.c zraloc.c zshlib.c zttyio.c zwmsec.c zxwhen.c zzdbg.c zzepro.c zzexit.c zzpstr.c zzsetk.c zzstrt.c alloc.c getproc.c
gcc: warning: couldn’t understand kern.osversion ‘18.5.0
gmttolst.c:4:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
irafpath.c:4:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
prwait.c:4:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
zalloc.c:4:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
zawset.c:4:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
zcall.c:4:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
zdojmp.c:4:20: fatal error: setjmp.h: No such file or directory
 #include <setjmp.h>
                    ^
compilation terminated.
zfacss.c:4:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
zfaloc.c:4:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
zfchdr.c:4:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
zfdele.c:4:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
zfgcwd.c:4:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
zfinfo.c:4:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
zfiobf.c:4:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>

**Comment by olebole** [comment]
Since 10.14 + XCode 10.2.1 [is one of the test environments on Travis](https://travis-ci.com/iraf-community/iraf/jobs/181810561), I am wondering whether something is broken with your XCode installation? Especially I am wondering about the gcc output 
```
gcc: warning: couldn’t understand kern.osversion ‘18.5.0
```
which seems that there is a problem with your C compiler (or XCode), before it touches any source file. Maybe that you have an older XCode version installed as well and the wrong one is taken here? What is the output of `gcc --version`?

Can you try to build a simple C program? Like
```
#include <stdio.h>

int main(void) {
    printf("Hello world\n");
    return 0;
}
```

**Comment by olebole** [comment]
@pmassey could you check that you installed xcode correctly and used the latest compiler? Since I assume that this is an installation problem, I would otherwise like to close the issue.

**Comment by pmassey** [comment]
Thanks very much for your suggestion that it was a gcc problem.  You were correct! Although  XCODE was installed properly (is it possible to install it improperly?), I had an older version of gcc in my bash path that was left over from the old HPC site. (I usually am running in the tcsh, which explains why I hadn't noticed this before.) When I removed it, the code compiled...mostly. I've attached a copy of the build.log below.
[build.log](https://github.com/iraf-community/iraf/files/3131210/build.log)


However, there were numerous warning messages, and at the end, when I ran the ./test/run_tests, I got: 
ecl.e: README.md 
ecl.e: files.md ......
ecl.e: images.imcoords.md ...........
ecl.e: images.imfilter.md .x............
ecl.e: images.imfit.md ...
ecl.e: images.imgeom.md ........
ecl.e: images.immatch.md ..
ecl.e: lists.md .......
ecl.e: noao.astutil.md ........
ecl.e: noao.digiphot.photcal.md .
ecl.e: numerical-recipes.md ..........
ecl.e: programming.md ............
ecl.e: test-syntax.md ...xs.
ecl.e: testproc.md .........................
ecl.e: utilities.nttools.md ..............
Test summary:  124 passed
   1 skipped
   2 xfailed
I was unable to locate any other output indicating where the problem was.

I haven't used the installation since then other than a few tests to substantiate that implot and display works properly, but I did notice one large functionality issue: when I went to the extern directory and ran ./configure, no Makefiles were produced, and I was unable to load stsdas or tables. Is this a problem with the installation or has this functionality not yet been implemented?  Until this is resolved, I've removed the code and reverted to my old NOAO version.

Thanks again for all of your help!

Best regards,
Phil

**Comment by olebole** [comment]
>I had an older version of gcc in my bash path that was left over from the old HPC site. (I usually am running in the tcsh, which explains why I hadn't noticed this before.)

You don't need to use bash here -- the scripts are now all `/bin/sh`, and you can start them from anywhere, even from a tcsh. They would inherit you `PATH` from there then.

> However, there were numerous warning messages, and at the end, when I ran the ./test/run_tests, I got:
> ```
> ecl.e: README.md
> ecl.e: files.md ......
> ecl.e: images.imcoords.md ...........
> ecl.e: images.imfilter.md .x............
> ecl.e: images.imfit.md ...
> ecl.e: images.imgeom.md ........
> ecl.e: images.immatch.md ..
> ecl.e: lists.md .......
> ecl.e: noao.astutil.md ........
> ecl.e: noao.digiphot.photcal.md .
> ecl.e: numerical-recipes.md ..........
> ecl.e: programming.md ............
> ecl.e: test-syntax.md ...xs.
> ecl.e: testproc.md .........................
> ecl.e: utilities.nttools.md ..............
> Test summary: 124 passed
> 1 skipped
> 2 xfailed
> ```
> I was unable to locate any other output indicating where the problem was.

That looks fine. The skipped test was so on purpose, and "xfailed" means that these are e**x**pected **fail**ures. So, you got a complete, tested installation.

>  I did notice one large functionality issue: when I went to the extern directory and ran ./configure, no Makefiles were produced, and I was unable to load stsdas or tables. Is this a problem with the installation or has this functionality not yet been implemented?

This will not work until a good soul digs into here. As you probably know, the NOAO distribution is now offline, and nobody volunteered to set up a replacement yet. 

One of the major (and probably unresolvable) problems is that the license of the external packages is often unclear. For some of the packages that were maintained by NOAO I asked and got the confirmation that they are under the IRAF license (mscred, fitsutil, sptable), while for the others it is still unclear.

For the STScI packages, the situation is even worse: They clearly contain non-distributable code (from the Numerical Recipes) book, and therefore can't be distributed anymore. Also the license that was applied by STScI on their own code was quite restrictive. And since the STScI code is restricted to 32 bit platforms (and absolutely not trivial to port to 64 bit), I am afraid that we will see it completing its death really soon. However, part of the "tables" package survived in the IRAF sptable package, where the sources are [here](https://github.com/iraf-community/iraf-sptable). Maybe, this will help you at least partially?

I will close this bug now, since its initial problem was solved. If you think that the handling of external packages must be solved, please open another issue (which I would keep open then).
