### ISSUE TITLE
stsdas and table installation

### ISSUE THREAD

**Issue by azim7091** [iraf-community/iraf#99]
Dear All, 
I have installed IRAF on Fedora (https://iraf-community.github.io/install). But there is not stsdas and table package in it. How can I install stsdas and table packages ?

Thanks in advance
Best Regards
Azim

**Comment by olebole** [comment]
The `tables.ttools` package was integrated into IRAF since version 2.15.1 as `utilities/nttools`. The `stsdas` package and the rest of `tables` however were separately maintained by STScI and are abandoned since 2018. They are not maintained by the iraf-community, since the sources are not available, and they contain code from the "Numerical Recipes" book which is forbidden to distribute.
